### ISSUE TITLE
setup.exe doesn't run on Windows 7

### ISSUE THREAD

**Issue by juristr** [JabbR/JabbR.Desktop#1]
Launching the setup.exe on my Win7 machine gives the following.

![image](https://f.cloud.github.com/assets/542458/1170803/b0323e94-20ef-11e3-919e-c52dbb15a5ab.png)

Any ideas??

Furthermore I cloned the repo and tried to build it by myself and also in that case I get an error saying the following:

![image](https://f.cloud.github.com/assets/542458/1170807/d2e98bcc-20ef-11e3-97e0-b098a54c9ad0.png)

thx for any help

**Comment by cwensley** [comment]
Both these issues should be fixed now.

Thanks for reporting!
